# Refit the original Sage force field on the new data set

# step 1 - generate force field - is nearly done, simply load the force field
# and dump it back out
initial.offxml: initial.py
	python initial.py

# step 2 - curate data set - is the same process, but with a different
# --initial-forcefield argument, meaning we need to duplicate the process here
